name = "refresh-notion-task-tracker-dispatcher"
main = "src/index.ts"
compatibility_date = "2026-07-17"

[triggers]
crons = ["0 0 * * *"]

[vars]
GITHUB_OWNER = "alovya"
GITHUB_REPOSITORY = "notion_task_tracker"
GITHUB_API_VERSION = "2022-11-28"
GITHUB_NOTION_TASK_CHANGE_EVENT_TYPE = "refresh-notion-task-tracker"
GITHUB_GOOGLE_CALENDAR_CHANGE_EVENT_TYPE = "apply-google-calendar-changes-to-notion-task-tracker"

[[d1_databases]]
binding = "GOOGLE_CALENDAR_STATE_DATABASE"
database_name = "google-calendar-state-database"
database_id = "36db3fc5-d250-4d47-aceb-5b280d686969"
migrations_dir = "migrations"
